### ISSUE TITLE
Configuration: `database_name` is invalid

### ISSUE THREAD

**Issue by chrisarcand** [InfluxCommunity/influxdb-rails#34]
Unless the purpose is much different from what it seems, the method [`database_name` in the configuration API](https://github.com/influxdata/influxdb-rails/blob/e9e11a71e02698b45f0760a58194b0734a7398e0/lib/influxdb/rails/configuration.rb#L142-L144) serves no purpose and is invalid, as `influxdb_database` is really the option that matters. `application_id` is also not used anywhere else.

I didn't make a pull request as I can't tell the intention here and what would be a breaking change vs a bug. Should it be removed entirely, utilize `influxdb_database` if set or not instead, etc...?

Either way it was confusing to explicitly configure my database name with `config.influxdb_database` and then find `InfluxDB::Rails.configuration.database_name` to be blank (`""`) 😕

**Comment by dmke** [comment]
This looks to me as an refactoring artifact.

Since it really seems not to be used (anymore), I'm all for removing it in a future release. For the near future, I'd issue a warning, either to `STDERR.puts` or using [`Module#deprecate` from ActivSupport](http://api.rubyonrails.org/classes/Module.html#method-i-deprecate).

A pull request is very welcome :-)

**Comment by chrisarcand** [comment]
👍 Making sure there wasn't some hidden intent I was missing 😄
