### ISSUE TITLE
How to add fields?

### ISSUE THREAD

**Issue by plum-dawg** [InfluxCommunity/influxdb-rails#36]
Does this gem have support for field metadata?

https://docs.influxdata.com/influxdb/v1.2/concepts/glossary/#field

**Comment by dmke** [comment]
No (not yet at least). Do you have something concrete in mind? It should be possible to provide callbacks for extra tags and fields (fields are named `values` in the underlying `influxdb` gem).

For the time being, you can easily add a `before/around/after_action` to your controller and write a point manually via `InfluxDB::Rails.client.write_point`. I can see the problem though, that you might loose the correlation between your data point and the instrumentation data points, due to (slightly) different timestamps.

FYI, these are the current call sites: [search results for `write_point -path:spec extension:rb`](https://github.com/influxdata/influxdb-rails/search?q=write_point+-path%3Aspec+extension%3Arb) (mainly in `lib/influxdb-rails.rb` in the `handle_action_controller_metrics` method).

**Comment by dmke** [comment]
In #30, something similar was requested. I'm accepting PRs for this, if you want to take a look :-)
