### ISSUE TITLE
Idea: A Series that tracks new model creation

### ISSUE THREAD

**Issue by vassilevsky** [InfluxCommunity/influxdb-rails#38]
1 new model = 1 event sent to InfluxDB. Model class is a field.

Pretty useful metric.

**Comment by dmke** [comment]
I don't know if that is universally useful. InfluxBD tracks time series, not events.

A time series metric would be the total number of model records over time, which could easily be implemented as such:

```rb
class ApplicationRecord
  after_create :influx_record_metrics
  after_destroy :influx_record_metrics 

private

  def influx_record_metrics
    InfluxDB::Rails.client..write_point "models",
      tags: { class: self.class.name },
      values: { n: self.class.unscoped.count }
  end
end
```

*However*, if the question you'd want to answer is "how many Users have registered between X and Y?", you propably need to fall back to SQL anyway, because a typical User registration is finished after the E-mail address has been verified (not after the User record was created).

And if you're interested in the number of Comments in the last day, `Comment.where("created_at > ?", 1.day.ago).count` is a *much* easier alternative (RDMS are good at counting records).

**Comment by dmke** [comment]
Closing this now.

If you ever come around to building this (and releasing it as gem), let me know. I'll add it to the readme :-)
