### ISSUE TITLE
how to handle all exceptions in influxdb-rails?

### ISSUE THREAD

**Issue by ghost** [InfluxCommunity/influxdb-rails#46]
i got this issue:
Cannot write data: #<InfluxDB::Error: {"error":"database not found: \"rails\""}

so I used rescue but not working

           begin
            influxdb.write_point(db_name,data) 
           rescue InfluxDB::Error => e 
             puts e.errors 
           end

**Comment by dmke** [comment]
This should work. All errors are subclassed from `InfluxDB::Error` (see [definition here](https://github.com/influxdata/influxdb-ruby/blob/master/lib/influxdb/errors.rb)).

What version of `influxdb-rails` *and* `influxdb-ruby` are you using?

I also noted `puts e.errors`; the [Exception](http://ruby-doc.org/core/Exception.html) class however does not have such a method. What is your exact error output?

**Comment by ghost** [comment]
It would be better if you tell me how to deal with an exception.
Basically, I got this issue "Cannot write data: #<InfluxDB::Error: {"error":"database not found: "rails""} " in log file.
and I want to handle this type of issues by using the rescue. but never calls rescue part.

**Comment by dmke** [comment]
All possible exceptions which could occour when writing points are listed in [`InfluxDB::HTTP`](https://github.com/influxdata/influxdb-ruby/blob/master/lib/influxdb/client/http.rb):

- method `post` (l. 24ff) is your entry point
- `connect_with_retry` performs the HTTP transfer and wraps any connection errors in an `InfluxDB::ConnectionError` (l. 55 and 59)
- if the server response indicates missing or invalid credentials, `post` raises an `InfluxDB::AuthenticationError` (l. 33)
- if the server response contains encodes an error, `resolve_error` (called in l. 35 and defined in l. 80ff) will raise an `InfluxDB::SeriesNotFound` or a generic `InfluxDB::Error`

As [mentioned before](https://github.com/influxdata/influxdb-ruby/blob/master/lib/influxdb/errors.rb), all these errors are defined as follows:

- `class InfluxDB::Error < StandardError` most generic error class
- `class InfluxDB::AuthenticationError < InfluxDB::Error`
- `class InfluxDB::ConnectionError < InfluxDB::Error`
- `class InfluxDB::SeriesNotFound < InfluxDB::Error`

Hence,

```ruby
begin
  influxdb.write_points(...)
rescue InfluxDB::Error => e
end
```

*should* catch all InfluxDB-related errors.

> It would be better if you tell me how to deal with an exception.

Well, if you have an

````ruby
puts e.errors 
````

in your `rescue` block, you will get a `NoMethodError` (`'errors' for InfluxDB::Error`) or similar, because **there is no `errors` method**, which will likely end up in your logs.

Other than that: sorry. Without further information I cannot help you. What are your exact versions of `influxdb-ruby`, `influxdb-rails` and Ruby?

**Comment by ghost** [comment]
ruby version: 2.5.1
influxdb-rails 0.4.3
influxdb 0.5.3

**Comment by dmke** [comment]
Sorry for letting you hang here, I forgot about this issue.

Turns out, I've misread the initial description. The error `database not found: "rails"` indicates that you don't have a db with that name *on the server*. To create one, execute the following command:

```console
$ influx -execute 'CREATE DATABASE rails'
```
