### ISSUE TITLE
Multiple Series vs Field Values

### ISSUE THREAD

**Issue by jjculber** [InfluxCommunity/influxdb-rails#48]
Hi, I'm curious what advantages there are to posting the controller, db, and view data as separate series? (see https://github.com/influxdata/influxdb-rails/blob/master/lib/influxdb-rails.rb#L99)

I'm still learning influxdb, but it seems possible to save it as a single series with multiple field values instead of a single one named `value`. My reasoning behind the question is I believe the values for the controller series include the times for db and views as well so I'd like to subtract it out. The easiest way I've found to do that is a query like `SELECT "rails.controller" - "rails.db" - "rails.view", "rails.db", "rails.view" from metrics where time > now() - 2m`, but that only works if they're in the same measurement. It seems like it would be easier for graphing applications like grafana if it was in a single query, too. Currently it's a separate query for each.

**Comment by dmke** [comment]
You're right, a common measurement would be more sensible. The decision to split the timing across multiple measurements was made long before I started maintaining this library. So for the sake of existing tools there's no easy way to change this.

As a workaround, you could do this with a `CONTINUOUS QUERY` and copy the timing values into a common measurement, from where you can easily calculate the difference.

**Comment by dmke** [comment]
I might add another way to store the timing values, by (conditionally) writing into a 4th measurement. To keep backward-compatibility, the user would need to opt-in via configuration, like so:

```ruby
config.series_name_for_runtimes = "rails.timings"
config.store_timings_as = "single-series" # or "multi-series", "both"
```

where "multi-series" would be the current split across three series (and the default value). For "single-series", only `series_name_for_runtimes` would be written to. "both" would write to all four measurements, and is primarily intended for the migration of the toolchain downstream.

Aside from having less overhead when reading/calculating difference values, the "single-series" storage reduces disk space requirements, because the tags are not duplicated three times (InfluxDB creates per-measurement indices over the tag set).

**Comment by jjculber** [comment]
Thanks for the very helpful reply!

**Comment by jjculber** [comment]
If anyone happens to find this later, I found a workaround in grafana so I don't need to do any math. I can set a Series Override for rails.controller to set `stack: false` and turn stacking on in the draw options and the result graph looks correct.

**Comment by dmke** [comment]
FYI, for the upcoming 1.0 release, I've decided to move to a common measurement: #56.

There's no time estimaton for this though (as I'm doing this in my free time).
